server:
  port: 8087
spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.13.28.164:3306/leyou?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ly:
  jwt:
    secret: ly@Login(Auth}*^31)&yun6%f3q2 # 登录校验的密钥
    pubKeyPath: C:/Users/yangfang/Desktop/rsa/id_rsa.pub # 公钥地址
    priKeyPath: C:/Users/yangfang/Desktop/rsa/id_rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN
    cookieMaxAge: 1800
logging:
  level:
    com:
      leyou:
        auth: DEBUG