server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
#  instance: 静态IP
#    prefer-ip-address: true
#    ip-address: 127.0.0.1
zuul:
  prefix: /api
  routes:
    item-service: /item/**
    user-service: /user/**
    auth-service: /auth/**
    #cart-service: /cart/**
    #order-service: /order-service/**
    #upload-service:
      #path: /upload/**
      #service: upload-service
      #strip-prefix: false
    #search-service: /search/**
  sensitive-headers:  #覆盖默认敏感头信息(不设置cookie会被拦截)
  add-host-header: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000
ribbon:
  connetTimeout: 500
  readTimeout: 5000
ly:
  jwt:
    pubKeyPath: /C:/Users/yangfang/Desktop/rsa/id_rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
    - /api/auth
    - /api/search
    - /api/user/register
    - /api/user/check
    - /api/user/code
    #- /api/item

