
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
#  instance:
#    prefer-ip-address: true
#    ip-address: 127.0.0.1
spring:
  application:
    name: item-service
  #消息队列配置
  rabbitmq:
    host: 106.13.28.164
    username: yangfng
    password: 123456
    virtual-host: /yangfang
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
      exchange: ly.item.exchange #配置默认交换机
    publisher-confirms: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.13.28.164:3306/leyou?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456